apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-app
spec:
  selector:
    app: nextjs
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
